version: '3'

services:
  php:
    build: './php-h5p-service'
    volumes:
      - "./php-h5p-app:/var/www/html"
      - "./php-h5p-service/config/php.ini:/usr/local/etc/php/php.ini"
      - "./laravel-h5p:/var/www/thomasmars/laravel-h5p/"
    ports:
      - "9000:9000"
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    ports:
      - "3306:3306"
  nginx:
    image: nginx:latest
    volumes:
      - "./configs/default.conf:/etc/nginx/conf.d/default.conf"
      - "./php-h5p-app:/var/www/html"
    ports:
      - "80:80"
